import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  // smoke-*.spec.js is auto-generated by generate-specs.js and gitignored. logged-out.spec.js,
  // logged-out-nav.spec.js, and no-nan.spec.js are hand-written and tracked, so they need their own
  // testMatch entries to run alongside them.
  testMatch: ['smoke-*.spec.js', 'logged-out.spec.js', 'logged-out-nav.spec.js', 'no-nan.spec.js'],
  timeout: 30_000,
  expect: { timeout: 10_000 },
  retries: 0,
  // Playwright parallelises by FILE by default, so no-nan.spec.js's ~105 independent route tests all
  // queued behind one worker - 6.7 of the suite's 6.8 minutes. Its tests share no state (each opens
  // its own context and navigates), so they can run in parallel. The generated smoke-*.spec.js files
  // opt back out with their own `test.describe.configure({ mode: 'serial' })`, which wins over this,
  // because they share a worker-scoped demo page and navigate it in sequence.
  fullyParallel: true,
  // Deliberately still 4, not higher: the bottleneck past this point is `next dev` (single server,
  // compiling routes on demand), not the CPU. At 8 workers the whole suite got no faster and
  // logged-out-nav started failing on contention alone.
  workers: 4,
  reporter: 'list',
  use: {
    baseURL: 'http://localhost:3001',
    headless: true,
  },
  webServer: {
    command: 'npm run dev',
    url: 'http://localhost:3001',
    reuseExistingServer: true,
    timeout: 60_000,
  },
});
