import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  // smoke-*.spec.js is auto-generated by generate-specs.js and gitignored. logged-out.spec.js,
  // logged-out-nav.spec.js, and no-nan.spec.js are hand-written and tracked, so they need their own
  // testMatch entries to run alongside them.
  testMatch: ['smoke-*.spec.js', 'logged-out.spec.js', 'logged-out-nav.spec.js', 'no-nan.spec.js'],
  timeout: 30_000,
  expect: { timeout: 10_000 },
  retries: 0,
  // Playwright parallelises by FILE by default, so no-nan.spec.js's ~105 independent route tests all
  // queued behind one worker - 6.7 of the suite's 6.8 minutes. Its tests share no state (each opens
  // its own context and navigates), so they can run in parallel. The generated smoke-*.spec.js files
  // opt back out with their own `test.describe.configure({ mode: 'serial' })`, which wins over this,
  // because they share a worker-scoped demo page and navigate it in sequence.
  fullyParallel: true,
  // Was 4 to avoid overloading `next dev`. The static build has no per-route compilation, so the
  // server is no longer the bottleneck and this can rise if the CPU allows.
  workers: 4,
  reporter: 'list',
  use: {
    // Every spec navigates with a relative path so the port lives here alone. 3002, not the dev
    // server's 3001, so `npm run dev` can stay up while the suite runs against the build.
    baseURL: 'http://localhost:3002',
    headless: true,
  },
  /**
   * Serves the static export, not `next dev`. `output: 'export'` means `out/` on a plain file
   * server is what ships, and `next dev`'s on-demand route compilation was the source of two
   * classes of flake here (cold routes blowing render-wait caps, ad scripts blocking networkidle).
   *
   * `reuseExistingServer: false` so a dev server left on this port cannot silently substitute for
   * the build. `npm run test:e2e` builds first; `test:e2e:nobuild` reuses an existing `out/`.
   */
  webServer: {
    command: 'npm run serve:e2e',
    url: 'http://localhost:3002',
    reuseExistingServer: false,
    timeout: 120_000,
  },
});
