import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  // smoke-*.spec.js is auto-generated by generate-specs.js and gitignored. logged-out.spec.js and
  // logged-out-nav.spec.js are hand-written and tracked, so they need their own testMatch entries
  // to run alongside them.
  testMatch: ['smoke-*.spec.js', 'logged-out.spec.js', 'logged-out-nav.spec.js'],
  timeout: 30_000,
  expect: { timeout: 10_000 },
  retries: 0,
  workers: 4,
  reporter: 'list',
  use: {
    baseURL: 'http://localhost:3001',
    headless: true,
  },
  webServer: {
    command: 'npm run dev',
    url: 'http://localhost:3001',
    reuseExistingServer: true,
    timeout: 60_000,
  },
});
