// Auto-generated
// Do not edit manually

/** Sparse array-like object from Firebase: { "0": val, "1": val, ..., "length": N } */
export type SparseArray = Record<string, number> & { length: number };

/**
 * Raw save data from Firebase / cloud save.
 * Many string values are JSON-encoded and need tryToParse().
 * Per-character fields are accessed via _N suffix: idleonData[`Key_${charIndex}`]
 */
export interface IdleonData {
  // ── Account-wide fields ──────────────────────────────────
  AchieveReg: number[];
  AnvilCraftStatus: any[][];
  ArcadeUpg: number[];
  Arcane: number[];
  ArcUnclaim: Record<string, any>;
  Atoms: number[];
  BGsel: number;
  BGunlocked: number[];
  bin_a: number;
  bin_b: number;
  bin_c: number;
  bin_i: number;
  bin_j: number;
  Boats: any[][];
  bon_a: number;
  bon_c: number;
  bon_d: number;
  bon_e: number;
  bon_f: number;
  bon_g: number;
  bon_h: number;
  bon_i: number;
  bon_j: number;
  bon_k: number;
  bon_l: number;
  bon_m: number;
  bon_n: number;
  bon_o: number;
  bon_p: number;
  bon_r: number;
  bon_s: number;
  bon_t: number;
  BossInfo: SparseArray[];
  Breeding: any[][];
  BribeStatus: number[];
  Bubba: any[][];
  BugInfo: any[][];
  bun_a: number;
  bun_b: number;
  bun_c: number;
  bun_d: number;
  bun_e: number;
  bun_f: number;
  bun_g: number;
  bun_h: number;
  bun_i: number;
  bun_j: number;
  bun_k: number;
  bun_l: number;
  bun_m: number;
  bun_n: number;
  bun_o: number;
  bun_p: number;
  bun_q: number;
  bun_r: number;
  bun_s: number;
  bun_t: number;
  bun_u: number;
  bun_v: number;
  bun_w: number;
  bun_x: number;
  bun_y: number;
  bun_z: number;
  BundlesReceived: Record<string, any>;
  Captains: any[][];
  Cards0: Record<string, any>;
  Cards1: string[];
  CauldronBubbles: any[][];
  CauldronInfo: any[];
  CauldronJobs0: any[][];
  CauldronJobs1: number[];
  CauldronP2W: any[][];
  CauldUpgLVs: number[];
  CauldUpgXPs: number[];
  ChestOrder: string[];
  ChestQuantity: number[];
  CloudsaveTimer: number;
  CMm: Record<string, any>;
  CMmLENGTH: number;
  CogM: Record<string, any>;
  CogO: string[];
  Compass: any[][];
  Cooking: any[][];
  CSver: number;
  CYAFKdoubles: number;
  CYAnvilTabsOwned: number;
  CYCharSlotsMTX: number;
  CYColosseumTickets: number;
  CYDeliveryBoxComplete: number;
  CYDeliveryBoxMisc: number;
  CYDeliveryBoxStreak: number;
  CYGems: number;
  CYGoldPens: number;
  CYKeysAll: number[];
  CYNPC: number[];
  CYObolFragments: number;
  CYSilverPens: number;
  CYTalentPoints: number[];
  CYWorldTeleports: number;
  Divinity: number[];
  DoOnceREAL: number;
  Dream: number[];
  DungUpg: any[][];
  FamValColosseumHighscores: any[];
  FamValFishingToolkitOwned: SparseArray[];
  FamValMinigameHiscores: number[];
  FamValWorldSelected: number;
  FarmCrop: Record<string, any>;
  FarmPlot: any[][];
  FarmRank: any[][];
  FarmUpg: number[];
  FlagP: number[];
  FlagU: number[];
  ForgeIntProg: number[];
  ForgeItemOrder: string[];
  ForgeItemQty: number[];
  ForgeLV: number[];
  Gaming: any[];
  GamingSprout: any[][];
  GemItemsPurchased: number[];
  GemsOwned: number;
  GemsPacksPurchased: number;
  Grimoire: number[];
  Guild: any[][];
  HintStatus: any[][];
  Holes: any[][];
  InvStorageUsed: Record<string, any>;
  Jars: any[][];
  KRbest: Record<string, any>;
  Lab: any[][];
  MapBon: any[][];
  Meals: any[][];
  MoneyBANK: number;
  Ninja: any[][];
  ObolEqMAPz1: Record<string, any>;
  ObolEqMAPz2: Record<string, any>;
  ObolEqO1: string[];
  ObolEqO2: string[];
  ObolInvOr: any[];
  ObolInvOwn: number[];
  OptLacc: number[];
  Pets: any[][];
  PetsStored: any[][];
  PostOfficeInfo0: any[];
  PostOfficeInfo1: any[];
  PostOfficeInfo2: SparseArray[];
  PrayOwned: number[];
  Print: any[];
  PrinterXtra: any[];
  Refinery: any[][];
  Research: any[][];
  Ribbon: number[];
  Rift: any[];
  SailChests: any[];
  Sailing: any[][];
  SaltLick: number[];
  ServerGems: number;
  ServerGemsReceived: number;
  ShopStock: SparseArray[];
  Shrine: any[][];
  Spelunk: any[][];
  SSprog: any[][];
  StampLv: SparseArray[];
  StampLvM: SparseArray[];
  StarSg: Record<string, any>;
  SteamAchieve: number[];
  StuG: number[];
  Summon: any[][];
  TaskZZ0: any[][];
  TaskZZ1: any[][];
  TaskZZ2: any[][];
  TaskZZ3: any[][];
  TaskZZ4: number[];
  TaskZZ5: number[];
  Territory: any[][];
  Tess: any[][];
  TimeAway: Record<string, any>;
  TotemInfo: any[][];
  Tower: number[];
  UpgVault: number[];
  WeeklyBoss: Record<string, any>;

  // ── Per-character fields (typed for each character index) ──
  'AFKtarget_0'?: string;
  'AFKtarget_1'?: string;
  'AFKtarget_2'?: string;
  'AFKtarget_3'?: string;
  'AFKtarget_4'?: string;
  'AFKtarget_5'?: string;
  'AFKtarget_6'?: string;
  'AFKtarget_7'?: string;
  'AFKtarget_8'?: string;
  'AFKtarget_9'?: string;
  'AnvilPA_0'?: any[];
  'AnvilPA_1'?: any[];
  'AnvilPA_2'?: any[];
  'AnvilPA_3'?: any[];
  'AnvilPA_4'?: any[];
  'AnvilPA_5'?: any[];
  'AnvilPA_6'?: any[];
  'AnvilPA_7'?: any[];
  'AnvilPA_8'?: any[];
  'AnvilPA_9'?: any[];
  'AnvilPAselect_0'?: number[];
  'AnvilPAselect_1'?: number[];
  'AnvilPAselect_2'?: number[];
  'AnvilPAselect_3'?: number[];
  'AnvilPAselect_4'?: number[];
  'AnvilPAselect_5'?: number[];
  'AnvilPAselect_6'?: number[];
  'AnvilPAselect_7'?: number[];
  'AnvilPAselect_8'?: number[];
  'AnvilPAselect_9'?: number[];
  'AnvilPAstats_0'?: number[];
  'AnvilPAstats_1'?: number[];
  'AnvilPAstats_2'?: number[];
  'AnvilPAstats_3'?: number[];
  'AnvilPAstats_4'?: number[];
  'AnvilPAstats_5'?: number[];
  'AnvilPAstats_6'?: number[];
  'AnvilPAstats_7'?: number[];
  'AnvilPAstats_8'?: number[];
  'AnvilPAstats_9'?: number[];
  'AtkCD_0'?: Record<string, any>;
  'AtkCD_1'?: Record<string, any>;
  'AtkCD_2'?: Record<string, any>;
  'AtkCD_3'?: Record<string, any>;
  'AtkCD_4'?: Record<string, any>;
  'AtkCD_5'?: Record<string, any>;
  'AtkCD_6'?: Record<string, any>;
  'AtkCD_7'?: Record<string, any>;
  'AtkCD_8'?: Record<string, any>;
  'AtkCD_9'?: Record<string, any>;
  'AttackLoadout_0'?: any[][];
  'AttackLoadout_1'?: any[][];
  'AttackLoadout_2'?: any[][];
  'AttackLoadout_3'?: any[][];
  'AttackLoadout_4'?: any[][];
  'AttackLoadout_5'?: any[][];
  'AttackLoadout_6'?: any[][];
  'AttackLoadout_7'?: any[][];
  'AttackLoadout_8'?: any[][];
  'AttackLoadout_9'?: any[][];
  'AttackLoadoutpre_0'?: any[][];
  'AttackLoadoutpre_1'?: any[][];
  'AttackLoadoutpre_2'?: any[][];
  'AttackLoadoutpre_3'?: any[][];
  'AttackLoadoutpre_4'?: any[][];
  'AttackLoadoutpre_5'?: any[][];
  'AttackLoadoutpre_6'?: any[][];
  'AttackLoadoutpre_7'?: any[][];
  'AttackLoadoutpre_8'?: any[][];
  'AttackLoadoutpre_9'?: any[][];
  'BuffsActive_0'?: any[];
  'BuffsActive_1'?: any[];
  'BuffsActive_2'?: any[];
  'BuffsActive_3'?: any[];
  'BuffsActive_4'?: any[];
  'BuffsActive_5'?: any[];
  'BuffsActive_6'?: any[];
  'BuffsActive_7'?: any[];
  'BuffsActive_8'?: any[];
  'BuffsActive_9'?: any[];
  'CardEquip_0'?: string[];
  'CardEquip_1'?: string[];
  'CardEquip_2'?: string[];
  'CardEquip_3'?: string[];
  'CardEquip_4'?: string[];
  'CardEquip_5'?: string[];
  'CardEquip_6'?: string[];
  'CardEquip_7'?: string[];
  'CardEquip_8'?: string[];
  'CardEquip_9'?: string[];
  'CardPreset_0'?: any[][];
  'CardPreset_1'?: any[][];
  'CardPreset_2'?: any[][];
  'CardPreset_3'?: any[][];
  'CardPreset_4'?: any[][];
  'CardPreset_5'?: any[][];
  'CardPreset_6'?: any[][];
  'CardPreset_7'?: any[][];
  'CardPreset_8'?: any[][];
  'CardPreset_9'?: any[][];
  'CharacterClass_0'?: number;
  'CharacterClass_1'?: number;
  'CharacterClass_2'?: number;
  'CharacterClass_3'?: number;
  'CharacterClass_4'?: number;
  'CharacterClass_5'?: number;
  'CharacterClass_6'?: number;
  'CharacterClass_7'?: number;
  'CharacterClass_8'?: number;
  'CharacterClass_9'?: number;
  'CharSAVED_0'?: number;
  'CharSAVED_1'?: number;
  'CharSAVED_2'?: number;
  'CharSAVED_3'?: number;
  'CharSAVED_4'?: number;
  'CharSAVED_5'?: number;
  'CharSAVED_6'?: number;
  'CharSAVED_7'?: number;
  'CharSAVED_8'?: number;
  'CharSAVED_9'?: number;
  'CSetEq_0'?: Record<string, any>;
  'CSetEq_1'?: Record<string, any>;
  'CSetEq_2'?: Record<string, any>;
  'CSetEq_3'?: Record<string, any>;
  'CSetEq_4'?: Record<string, any>;
  'CSetEq_5'?: Record<string, any>;
  'CSetEq_6'?: Record<string, any>;
  'CSetEq_7'?: Record<string, any>;
  'CSetEq_8'?: Record<string, any>;
  'CSetEq_9'?: Record<string, any>;
  'CurrentMap_0'?: number;
  'CurrentMap_1'?: number;
  'CurrentMap_2'?: number;
  'CurrentMap_3'?: number;
  'CurrentMap_4'?: number;
  'CurrentMap_5'?: number;
  'CurrentMap_6'?: number;
  'CurrentMap_7'?: number;
  'CurrentMap_8'?: number;
  'CurrentMap_9'?: number;
  'EMm0_0'?: Record<string, any>;
  'EMm0_1'?: Record<string, any>;
  'EMm0_2'?: Record<string, any>;
  'EMm0_3'?: Record<string, any>;
  'EMm0_4'?: Record<string, any>;
  'EMm0_5'?: Record<string, any>;
  'EMm0_6'?: Record<string, any>;
  'EMm0_7'?: Record<string, any>;
  'EMm0_8'?: Record<string, any>;
  'EMm0_9'?: Record<string, any>;
  'EMm1_0'?: Record<string, any>;
  'EMm1_1'?: Record<string, any>;
  'EMm1_2'?: Record<string, any>;
  'EMm1_3'?: Record<string, any>;
  'EMm1_4'?: Record<string, any>;
  'EMm1_5'?: Record<string, any>;
  'EMm1_6'?: Record<string, any>;
  'EMm1_7'?: Record<string, any>;
  'EMm1_8'?: Record<string, any>;
  'EMm1_9'?: Record<string, any>;
  'EMmLENGTH0_0'?: number;
  'EMmLENGTH0_1'?: number;
  'EMmLENGTH0_2'?: number;
  'EMmLENGTH0_3'?: number;
  'EMmLENGTH0_4'?: number;
  'EMmLENGTH0_5'?: number;
  'EMmLENGTH0_6'?: number;
  'EMmLENGTH0_7'?: number;
  'EMmLENGTH0_8'?: number;
  'EMmLENGTH0_9'?: number;
  'EMmLENGTH1_0'?: number;
  'EMmLENGTH1_1'?: number;
  'EMmLENGTH1_2'?: number;
  'EMmLENGTH1_3'?: number;
  'EMmLENGTH1_4'?: number;
  'EMmLENGTH1_5'?: number;
  'EMmLENGTH1_6'?: number;
  'EMmLENGTH1_7'?: number;
  'EMmLENGTH1_8'?: number;
  'EMmLENGTH1_9'?: number;
  'EquipOrder_0'?: any[];
  'EquipOrder_1'?: any[];
  'EquipOrder_2'?: any[];
  'EquipOrder_3'?: any[];
  'EquipOrder_4'?: any[];
  'EquipOrder_5'?: any[];
  'EquipOrder_6'?: any[];
  'EquipOrder_7'?: any[];
  'EquipOrder_8'?: any[];
  'EquipOrder_9'?: any[];
  'EquipQTY_0'?: any[];
  'EquipQTY_1'?: any[];
  'EquipQTY_2'?: any[];
  'EquipQTY_3'?: any[];
  'EquipQTY_4'?: any[];
  'EquipQTY_5'?: any[];
  'EquipQTY_6'?: any[];
  'EquipQTY_7'?: any[];
  'EquipQTY_8'?: any[];
  'EquipQTY_9'?: any[];
  'Exp0_0'?: number[];
  'Exp0_1'?: number[];
  'Exp0_2'?: number[];
  'Exp0_3'?: number[];
  'Exp0_4'?: number[];
  'Exp0_5'?: number[];
  'Exp0_6'?: number[];
  'Exp0_7'?: number[];
  'Exp0_8'?: number[];
  'Exp0_9'?: number[];
  'ExpReq0_0'?: number[];
  'ExpReq0_1'?: number[];
  'ExpReq0_2'?: number[];
  'ExpReq0_3'?: number[];
  'ExpReq0_4'?: number[];
  'ExpReq0_5'?: number[];
  'ExpReq0_6'?: number[];
  'ExpReq0_7'?: number[];
  'ExpReq0_8'?: number[];
  'ExpReq0_9'?: number[];
  'FoodCD_0'?: number[];
  'FoodCD_1'?: number[];
  'FoodCD_2'?: number[];
  'FoodCD_3'?: number[];
  'FoodCD_4'?: number[];
  'FoodCD_5'?: number[];
  'FoodCD_6'?: number[];
  'FoodCD_7'?: number[];
  'FoodCD_8'?: number[];
  'FoodCD_9'?: number[];
  'FoodSlO_0'?: number;
  'FoodSlO_1'?: number;
  'FoodSlO_2'?: number;
  'FoodSlO_3'?: number;
  'FoodSlO_4'?: number;
  'FoodSlO_5'?: number;
  'FoodSlO_6'?: number;
  'FoodSlO_7'?: number;
  'FoodSlO_8'?: number;
  'FoodSlO_9'?: number;
  'IMm_0'?: Record<string, any>;
  'IMm_1'?: Record<string, any>;
  'IMm_2'?: Record<string, any>;
  'IMm_3'?: Record<string, any>;
  'IMm_4'?: Record<string, any>;
  'IMm_5'?: Record<string, any>;
  'IMm_6'?: Record<string, any>;
  'IMm_7'?: Record<string, any>;
  'IMm_8'?: Record<string, any>;
  'IMm_9'?: Record<string, any>;
  'IMmLENGTH_0'?: number;
  'IMmLENGTH_1'?: number;
  'IMmLENGTH_2'?: number;
  'IMmLENGTH_3'?: number;
  'IMmLENGTH_4'?: number;
  'IMmLENGTH_5'?: number;
  'IMmLENGTH_6'?: number;
  'IMmLENGTH_7'?: number;
  'IMmLENGTH_8'?: number;
  'IMmLENGTH_9'?: number;
  'InvBagsUsed_0'?: Record<string, any>;
  'InvBagsUsed_1'?: Record<string, any>;
  'InvBagsUsed_2'?: Record<string, any>;
  'InvBagsUsed_3'?: Record<string, any>;
  'InvBagsUsed_4'?: Record<string, any>;
  'InvBagsUsed_5'?: Record<string, any>;
  'InvBagsUsed_6'?: Record<string, any>;
  'InvBagsUsed_7'?: Record<string, any>;
  'InvBagsUsed_8'?: Record<string, any>;
  'InvBagsUsed_9'?: Record<string, any>;
  'InventoryOrder_0'?: string[];
  'InventoryOrder_1'?: string[];
  'InventoryOrder_2'?: string[];
  'InventoryOrder_3'?: string[];
  'InventoryOrder_4'?: string[];
  'InventoryOrder_5'?: string[];
  'InventoryOrder_6'?: string[];
  'InventoryOrder_7'?: string[];
  'InventoryOrder_8'?: string[];
  'InventoryOrder_9'?: string[];
  'ItemQTY_0'?: number[];
  'ItemQTY_1'?: number[];
  'ItemQTY_2'?: number[];
  'ItemQTY_3'?: number[];
  'ItemQTY_4'?: number[];
  'ItemQTY_5'?: number[];
  'ItemQTY_6'?: number[];
  'ItemQTY_7'?: number[];
  'ItemQTY_8'?: number[];
  'ItemQTY_9'?: number[];
  'KLA_0'?: any[][];
  'KLA_1'?: any[][];
  'KLA_2'?: any[][];
  'KLA_3'?: any[][];
  'KLA_4'?: any[][];
  'KLA_5'?: any[][];
  'KLA_6'?: any[][];
  'KLA_7'?: any[][];
  'KLA_8'?: any[][];
  'KLA_9'?: any[][];
  'LockedSlots_0'?: number[];
  'LockedSlots_1'?: number[];
  'LockedSlots_2'?: number[];
  'LockedSlots_3'?: number[];
  'LockedSlots_4'?: number[];
  'LockedSlots_5'?: number[];
  'LockedSlots_6'?: number[];
  'LockedSlots_7'?: number[];
  'LockedSlots_8'?: number[];
  'LockedSlots_9'?: number[];
  'Lv0_0'?: number[];
  'Lv0_1'?: number[];
  'Lv0_2'?: number[];
  'Lv0_3'?: number[];
  'Lv0_4'?: number[];
  'Lv0_5'?: number[];
  'Lv0_6'?: number[];
  'Lv0_7'?: number[];
  'Lv0_8'?: number[];
  'Lv0_9'?: number[];
  'MaxCarryCap_0'?: Record<string, any>;
  'MaxCarryCap_1'?: Record<string, any>;
  'MaxCarryCap_2'?: Record<string, any>;
  'MaxCarryCap_3'?: Record<string, any>;
  'MaxCarryCap_4'?: Record<string, any>;
  'MaxCarryCap_5'?: Record<string, any>;
  'MaxCarryCap_6'?: Record<string, any>;
  'MaxCarryCap_7'?: Record<string, any>;
  'MaxCarryCap_8'?: Record<string, any>;
  'MaxCarryCap_9'?: Record<string, any>;
  'Money_0'?: number;
  'Money_1'?: number;
  'Money_2'?: number;
  'Money_3'?: number;
  'Money_4'?: number;
  'Money_5'?: number;
  'Money_6'?: number;
  'Money_7'?: number;
  'Money_8'?: number;
  'Money_9'?: number;
  'NPCdialogue_0'?: Record<string, any>;
  'NPCdialogue_1'?: Record<string, any>;
  'NPCdialogue_2'?: Record<string, any>;
  'NPCdialogue_3'?: Record<string, any>;
  'NPCdialogue_4'?: Record<string, any>;
  'NPCdialogue_5'?: Record<string, any>;
  'NPCdialogue_6'?: Record<string, any>;
  'NPCdialogue_7'?: Record<string, any>;
  'NPCdialogue_8'?: Record<string, any>;
  'NPCdialogue_9'?: Record<string, any>;
  'ObolEqMAP_0'?: Record<string, any>;
  'ObolEqMAP_1'?: Record<string, any>;
  'ObolEqMAP_2'?: Record<string, any>;
  'ObolEqMAP_3'?: Record<string, any>;
  'ObolEqMAP_4'?: Record<string, any>;
  'ObolEqMAP_5'?: Record<string, any>;
  'ObolEqMAP_6'?: Record<string, any>;
  'ObolEqMAP_7'?: Record<string, any>;
  'ObolEqMAP_8'?: Record<string, any>;
  'ObolEqMAP_9'?: Record<string, any>;
  'ObolEqO0_0'?: string[];
  'ObolEqO0_1'?: string[];
  'ObolEqO0_2'?: string[];
  'ObolEqO0_3'?: string[];
  'ObolEqO0_4'?: string[];
  'ObolEqO0_5'?: string[];
  'ObolEqO0_6'?: string[];
  'ObolEqO0_7'?: string[];
  'ObolEqO0_8'?: string[];
  'ObolEqO0_9'?: string[];
  'ObolInvMAP_0'?: Record<string, any>;
  'ObolInvMAP_1'?: Record<string, any>;
  'ObolInvMAP_2'?: Record<string, any>;
  'ObolInvMAP_3'?: Record<string, any>;
  'ObolInvMAP_4'?: Record<string, any>;
  'ObolInvMAP_5'?: Record<string, any>;
  'ObolInvMAP_6'?: Record<string, any>;
  'ObolInvMAP_7'?: Record<string, any>;
  'ObolInvMAP_8'?: Record<string, any>;
  'ObolInvMAP_9'?: Record<string, any>;
  'OptL_0'?: number[];
  'OptL_1'?: number[];
  'OptL_2'?: number[];
  'OptL_3'?: number[];
  'OptL_4'?: number[];
  'OptL_5'?: number[];
  'OptL_6'?: number[];
  'OptL_7'?: number[];
  'OptL_8'?: number[];
  'OptL_9'?: number[];
  'OptL2_0'?: SparseArray[];
  'OptL2_1'?: SparseArray[];
  'OptL2_2'?: SparseArray[];
  'OptL2_3'?: SparseArray[];
  'OptL2_4'?: SparseArray[];
  'OptL2_5'?: SparseArray[];
  'OptL2_6'?: SparseArray[];
  'OptL2_7'?: SparseArray[];
  'OptL2_8'?: SparseArray[];
  'OptL2_9'?: SparseArray[];
  'PlayerStuff_0'?: number[];
  'PlayerStuff_1'?: number[];
  'PlayerStuff_2'?: number[];
  'PlayerStuff_3'?: number[];
  'PlayerStuff_4'?: number[];
  'PlayerStuff_5'?: number[];
  'PlayerStuff_6'?: number[];
  'PlayerStuff_7'?: number[];
  'PlayerStuff_8'?: number[];
  'PlayerStuff_9'?: number[];
  'PldTraps_0'?: any[][];
  'PldTraps_1'?: any[][];
  'PldTraps_2'?: any[][];
  'PldTraps_3'?: any[][];
  'PldTraps_4'?: any[][];
  'PldTraps_5'?: any[][];
  'PldTraps_6'?: any[][];
  'PldTraps_7'?: any[][];
  'PldTraps_8'?: any[][];
  'PldTraps_9'?: any[][];
  'POu_0'?: number[];
  'POu_1'?: number[];
  'POu_2'?: number[];
  'POu_3'?: number[];
  'POu_4'?: number[];
  'POu_5'?: number[];
  'POu_6'?: number[];
  'POu_7'?: number[];
  'POu_8'?: number[];
  'POu_9'?: number[];
  'Prayers_0'?: number[];
  'Prayers_1'?: number[];
  'Prayers_2'?: number[];
  'Prayers_3'?: number[];
  'Prayers_4'?: number[];
  'Prayers_5'?: number[];
  'Prayers_6'?: number[];
  'Prayers_7'?: number[];
  'Prayers_8'?: number[];
  'Prayers_9'?: number[];
  'PTimeAway_0'?: number;
  'PTimeAway_1'?: number;
  'PTimeAway_2'?: number;
  'PTimeAway_3'?: number;
  'PTimeAway_4'?: number;
  'PTimeAway_5'?: number;
  'PTimeAway_6'?: number;
  'PTimeAway_7'?: number;
  'PTimeAway_8'?: number;
  'PTimeAway_9'?: number;
  'PVFishingSpotIndex_0'?: number;
  'PVFishingSpotIndex_1'?: number;
  'PVFishingSpotIndex_2'?: number;
  'PVFishingSpotIndex_3'?: number;
  'PVFishingSpotIndex_4'?: number;
  'PVFishingSpotIndex_5'?: number;
  'PVFishingSpotIndex_6'?: number;
  'PVFishingSpotIndex_7'?: number;
  'PVFishingSpotIndex_8'?: number;
  'PVFishingSpotIndex_9'?: number;
  'PVFishingToolkit_0'?: number[];
  'PVFishingToolkit_1'?: number[];
  'PVFishingToolkit_2'?: number[];
  'PVFishingToolkit_3'?: number[];
  'PVFishingToolkit_4'?: number[];
  'PVFishingToolkit_5'?: number[];
  'PVFishingToolkit_6'?: number[];
  'PVFishingToolkit_7'?: number[];
  'PVFishingToolkit_8'?: number[];
  'PVFishingToolkit_9'?: number[];
  'PVGender_0'?: number;
  'PVGender_1'?: number;
  'PVGender_2'?: number;
  'PVGender_3'?: number;
  'PVGender_4'?: number;
  'PVGender_5'?: number;
  'PVGender_6'?: number;
  'PVGender_7'?: number;
  'PVGender_8'?: number;
  'PVGender_9'?: number;
  'PVInstaRevives_0'?: number;
  'PVInstaRevives_1'?: number;
  'PVInstaRevives_2'?: number;
  'PVInstaRevives_3'?: number;
  'PVInstaRevives_4'?: number;
  'PVInstaRevives_5'?: number;
  'PVInstaRevives_6'?: number;
  'PVInstaRevives_7'?: number;
  'PVInstaRevives_8'?: number;
  'PVInstaRevives_9'?: number;
  'PVMinigamePlays_0'?: number;
  'PVMinigamePlays_1'?: number;
  'PVMinigamePlays_2'?: number;
  'PVMinigamePlays_3'?: number;
  'PVMinigamePlays_4'?: number;
  'PVMinigamePlays_5'?: number;
  'PVMinigamePlays_6'?: number;
  'PVMinigamePlays_7'?: number;
  'PVMinigamePlays_8'?: number;
  'PVMinigamePlays_9'?: number;
  'PVStatList_0'?: number[];
  'PVStatList_1'?: number[];
  'PVStatList_2'?: number[];
  'PVStatList_3'?: number[];
  'PVStatList_4'?: number[];
  'PVStatList_5'?: number[];
  'PVStatList_6'?: number[];
  'PVStatList_7'?: number[];
  'PVStatList_8'?: number[];
  'PVStatList_9'?: number[];
  'PVtStarSign_0'?: string;
  'PVtStarSign_1'?: string;
  'PVtStarSign_2'?: string;
  'PVtStarSign_3'?: string;
  'PVtStarSign_4'?: string;
  'PVtStarSign_5'?: string;
  'PVtStarSign_6'?: string;
  'PVtStarSign_7'?: string;
  'PVtStarSign_8'?: string;
  'PVtStarSign_9'?: string;
  'QuestComplete_0'?: Record<string, any>;
  'QuestComplete_1'?: Record<string, any>;
  'QuestComplete_2'?: Record<string, any>;
  'QuestComplete_3'?: Record<string, any>;
  'QuestComplete_4'?: Record<string, any>;
  'QuestComplete_5'?: Record<string, any>;
  'QuestComplete_6'?: Record<string, any>;
  'QuestComplete_7'?: Record<string, any>;
  'QuestComplete_8'?: Record<string, any>;
  'QuestComplete_9'?: Record<string, any>;
  'QuestHm_0'?: SparseArray[];
  'QuestHm_1'?: SparseArray[];
  'QuestHm_2'?: SparseArray[];
  'QuestHm_3'?: SparseArray[];
  'QuestHm_4'?: SparseArray[];
  'QuestHm_5'?: SparseArray[];
  'QuestHm_6'?: SparseArray[];
  'QuestHm_7'?: SparseArray[];
  'QuestHm_8'?: SparseArray[];
  'QuestHm_9'?: SparseArray[];
  'QuestStatus_0'?: Record<string, any>;
  'QuestStatus_1'?: Record<string, any>;
  'QuestStatus_2'?: Record<string, any>;
  'QuestStatus_3'?: Record<string, any>;
  'QuestStatus_4'?: Record<string, any>;
  'QuestStatus_5'?: Record<string, any>;
  'QuestStatus_6'?: Record<string, any>;
  'QuestStatus_7'?: Record<string, any>;
  'QuestStatus_8'?: Record<string, any>;
  'QuestStatus_9'?: Record<string, any>;
  'RespTime_0'?: number;
  'RespTime_1'?: number;
  'RespTime_2'?: number;
  'RespTime_3'?: number;
  'RespTime_4'?: number;
  'RespTime_5'?: number;
  'RespTime_6'?: number;
  'RespTime_7'?: number;
  'RespTime_8'?: number;
  'RespTime_9'?: number;
  'SL_0'?: Record<string, any>;
  'SL_1'?: Record<string, any>;
  'SL_2'?: Record<string, any>;
  'SL_3'?: Record<string, any>;
  'SL_4'?: Record<string, any>;
  'SL_5'?: Record<string, any>;
  'SL_6'?: Record<string, any>;
  'SL_7'?: Record<string, any>;
  'SL_8'?: Record<string, any>;
  'SL_9'?: Record<string, any>;
  'SLpre_0'?: Record<string, any>;
  'SLpre_1'?: Record<string, any>;
  'SLpre_2'?: Record<string, any>;
  'SLpre_3'?: Record<string, any>;
  'SLpre_4'?: Record<string, any>;
  'SLpre_5'?: Record<string, any>;
  'SLpre_6'?: Record<string, any>;
  'SLpre_7'?: Record<string, any>;
  'SLpre_8'?: Record<string, any>;
  'SLpre_9'?: Record<string, any>;
  'SM_0'?: Record<string, any>;
  'SM_1'?: Record<string, any>;
  'SM_2'?: Record<string, any>;
  'SM_3'?: Record<string, any>;
  'SM_4'?: Record<string, any>;
  'SM_5'?: Record<string, any>;
  'SM_6'?: Record<string, any>;
  'SM_7'?: Record<string, any>;
  'SM_8'?: Record<string, any>;
  'SM_9'?: Record<string, any>;
  'StatueLevels_0'?: any[][];
  'StatueLevels_1'?: any[][];
  'StatueLevels_2'?: any[][];
  'StatueLevels_3'?: any[][];
  'StatueLevels_4'?: any[][];
  'StatueLevels_5'?: any[][];
  'StatueLevels_6'?: any[][];
  'StatueLevels_7'?: any[][];
  'StatueLevels_8'?: any[][];
  'StatueLevels_9'?: any[][];

  // Allow dynamic access for character indices beyond 9
  [key: string]: any;
}

/** Guild data from Firebase */
export interface GuildData {
  stats?: any[][];
  members?: any[];
  points?: number;
  [key: string]: any;
}

/** Companion data from Firebase `_comp/{uid}` */
export interface CompanionData {
  d?: number;
  e?: string;
  l?: string[];
  o?: number[];
  s?: number;
  sd?: number;
  sp?: boolean[];
  t?: number;
  x?: number;
  y?: number;
  z22?: number;
  z23?: number;
  z24?: number;
  zm?: Record<string, any>;
  [key: string]: any;
}

/** Server variables from Firebase */
export interface ServerVars {
  '0TwitchLive'?: number;
  '0TwitchLiveDrops'?: number;
  '1LavaChat'?: string;
  A_divArc?: string;
  A_empoExpon?: number;
  A_MineCost?: number;
  A_MineHP?: number;
  A_ResXP?: number;
  abc?: number;
  AncientArtiPCT?: number;
  AncientOddPerIsland?: number;
  AprilFools?: number;
  ArcadeBonuses?: number[];
  ArcadeRotation?: string;
  ArcGballPCT?: number;
  AutoLoot?: number;
  ChipRepo?: number[];
  Comp_Raffle?: number;
  Comp_RaffleWinners?: string;
  CompBatch?: number;
  DampenServerPlayerMvmt?: number;
  DivCostAfter3?: number;
  Dungeon_CardMulti?: number;
  Dungeon_CredMulti?: number;
  Dungeon_FlurboMulti?: number;
  Dungeon1_time?: number;
  DustCost?: number;
  EventActive?: string;
  EventFun?: string;
  EventOddz?: number;
  EventTimerBypass?: number;
  EventVal1?: number;
  GameVERSION?: number;
  GamingFertCostExpA?: number;
  GemBundleOffer?: string;
  GemBundleOffer2?: string;
  GemBundleOffer3?: string;
  GemEvoOrder?: string;
  GemPM_x?: number;
  GemPopupBundle?: string;
  GemPopupLvREQ?: number;
  GuildRank?: string[];
  HappyHours?: number[];
  KillroySwap?: number;
  LavaHacks?: number;
  LetIOSin?: number;
  LtdShopNum?: number;
  NewStuffButton?: number;
  OfferBunC?: number;
  OGtrophy?: number;
  PCpurchases?: number;
  PristineCharm?: number;
  RandEvntHr?: number;
  RandEvntWorld?: number;
  RandomTest?: number;
  RateAgain?: number;
  RemoveVials?: number;
  StarterBundleReset?: number;
  SteamEvent?: number;
  Test?: string;
  TestData?: string;
  tgt_req?: number[];
  TomeOn?: number;
  TomePct?: number[];
  voteCat2?: number[];
  voteCategories?: number[];
  votePercent?: number[];
  votePercent2?: number[];
  WhateverKeyYouWant?: string;
  worldCounts?: number[];
  WorldSelRNG?: number;
  [key: string]: any;
}

/** Tournament server data from Firebase */
export interface TournamentData {
  user?: Record<string, any>;
  match?: Record<string, any>;
  global?: Record<string, any>;
  leaderboard?: any[];
  [key: string]: any;
}
