export const starSignsIndicesMap = {
  "The_Book_Worm": "1",
  "The_Buff_Guy": "1a",
  "The_Fuzzy_Dice": "1b",
  "Flexo_Bendo": "2",
  "Dwarfo_Beardus": "3",
  "Hipster_Logger": "4",
  "Pie_Seas": "4a",
  "Miniature_Game": "4b",
  "Shoe_Fly": "4c",
  "Pack_Mule": "5",
  "Pirate_Booty": "6",
  "All_Rounder": "7",
  "Muscle_Man": "7a",
  "Fast_Frog": "7b",
  "Smart_Stooge": "7c",
  "Lucky_Larry": "7d",
  "Fatty_Doodoo": "8",
  "Robinhood": "9",
  "Blue_Hedgehog": "9a",
  "Ned_Kelly": "10",
  "The_Fallen_Titan": "10a",
  "Chronus_Cosmos": "CR",
  "Activelius": "11",
  "Gum_Drop": "11a",
  "Mount_Eaterest": "12",
  "Bob_Build_Guy": "13",
  "The_Big_Comatose": "14",
  "Sir_Savvy": "14a",
  "Silly_Snoozer": "15",
  "The_Big_Brain": "15a",
  "Grim_Reaper": "16",
  "The_Forsaken": "16a",
  "The_OG_Skiller": "17",
  "Mr_No_Sleep": "18",
  "All_Rounderi": "1",
  "Centaurii": "2",
  "Murmollio": "3",
  "Strandissi": "4",
  "Agitagi": "4B",
  "Wispommo": "5",
  "Lukiris": "5B",
  "Pokaminni": "6",
  "Gor_Bowzor": "7",
  "Hydron_Cosmos": "8",
  "Trapezoidburg": "8B",
  "Sawsaw_Salala": "9",
  "Preys_Bea": "9B",
  "Cullingo": "10",
  "Gum_Drop_Major": "10B",
  "Grim_Reaper_Major": "11",
  "Sir_Savvy_Major": "12",
  "The_Bulwark": "13",
  "Big_Brain_Major": "14",
  "The_Fiesty": "15",
  "The_Overachiever": "15B",
  "Comatose_Major": "16",
  "S._Snoozer_Major": "17",
  // "Unknown":"18",
  // "Unknown":"19",
  // "Unknown":"19B",
  // "Unknown":"20",
  // "Unknown":"21",
  // "Unknown":"22",
  // "Unknown":"23",
}

// TODO: check if able to pull from Z.js
export const skillIndexMap = {
  0: { name: "character", icon: '' },
  1: { name: "mining", icon: 'ClassIcons42' },
  2: { name: "smithing", icon: 'ClassIcons43' },
  3: { name: "chopping", icon: 'ClassIcons44' },
  4: { name: "fishing", icon: 'ClassIcons45' },
  5: { name: "alchemy", icon: 'ClassIcons46' },
  6: { name: "catching", icon: 'ClassIcons47' },
  7: { name: "trapping", icon: 'ClassIcons48' },
  8: { name: "construction", icon: 'ClassIcons49' },
  9: { name: "worship", icon: 'ClassIcons50' },
  10: { name: 'cooking', icon: 'ClassIcons51' },
  11: { name: 'breeding', icon: 'ClassIcons52' },
  12: { name: 'laboratory', icon: 'ClassIcons53' },
  13: { name: 'sailing', icon: 'ClassIcons54' },
  14: { name: 'divinity', icon: 'ClassIcons55' },
  15: { name: 'gaming', icon: 'ClassIcons56' },
};


export const keysMap = {
  0: { name: "Forest_Villa_Key", rawName: 'Key1' },
  1: { name: "Efaunt's_Tomb_Key", rawName: 'Key2' },
  2: { name: "Chizoar's_Cavern_Key", rawName: 'Key3' },
  3: { name: "Troll's_Enclave_Key", rawName: 'Key4' }
};

export const filteredLootyItems = {
  'null': true,
  EquipmentShirts4: true,
  EquipmentShirts6: true,
  EquipmentShirts8: true,
  EquipmentShirts9: true,
  EquipmentShoes2: true,
  EquipmentShoes6: true,
  EquipmentShoes8: true,
  EquipmentShoes10: true,
  EquipmentShoes13: true,
  EquipmentShoes11: true,
  EquipmentShoes12: true,
  EquipmentShoes14: true,
  EquipmentPendant1: true,
  EquipmentPendant2: true,
  EquipmentPendant3: true,
  EquipmentPendant4: true,
  EquipmentPendant5: true,
  EquipmentPendant6: true,
  EquipmentPendant7: true,
  EquipmentPendant8: true,
  EquipmentPendant13: true,
  EquipmentPendant15: true,
  EquipmentPendant18: true,
  EquipmentRings1: true,
  EquipmentRings4: true,
  EquipmentRings5: true,
  EquipmentRings8: true,
  EquipmentRings9: true,
  EquipmentRings10: true,
  EquipmentRingsFishing1: true,
  EquipmentRingsFishing2: true,
  EquipmentRingsFishing3: true,
  EquipmentHatsBeg1: true,
  EquipmentHats10: true,
  EquipmentHats23: true,
  EquipmentHats24: true,
  EquipmentHats27: true,
  EquipmentWeapons1: true,
  EquipmentWeapons2: true,
  EquipmentWands3: true,
  EquipmentWands4: true,
  TestObj2: true,
  TestObj3: true,
  TestObj4: true,
  TestObj5: true,
  TestObj8: true,
  TestObj14: true,
  TestObj15: true,
  TestObj16: true,
  EquipmentPants7: true,
  EquipmentPants8: true,
  EquipmentPants9: true,
  EquipmentPants11: true,
  EquipmentPants12: true,
  EquipmentPants13: true,
  EquipmentPants14: true,
  Blank: true,
  LockedInvSpace: true,
  FillerMaterial: true,
  Fish5: true,
  Fish6: true,
  Fish7: true,
  Fish8: true,
  EquipmentSmithingTabs5: true,
  EquipmentSmithingTabs6: true,
  EquipmentSmithingTabs7: true,
  EquipmentSmithingTabs8: true,
  StampA22: true,
  StampA25: true,
  StampA29: true,
  StampA30: true,
  StampA31: true,
  StampA32: true,
  StampA33: true,
  StampA34: true,
  StampA35: true,
  CraftMat11: true,
  CraftMat12: true,
  CraftMat13: true,
  CraftMat14: true,
  CraftMat15: true,
  CraftMat16: true,
  CraftMat17: true,
  GemQ1: true,
  GemQ2: true,
  GemQ3: true,
  GemQ4: true,
  GemQ5: true,
  GemQ6: true,
  GemQ7: true,
  GemQ8: true,
  GemQ10: true,
  GemQ11: true,
  GemQ12: true,
  GemQ13: true,
  GemQ14: true,
  GemQ15: true,
  GemQ16: true,
  EquipmentHats35: true,
  EquipmentHats38: true,
  EquipmentHats46: true,
  EquipmentHats47: true,
  EquipmentHats48: true,
  EquipmentHats49: true,
  EquipmentHats50: true,
  CardPack1: true,
  CardPack2: true,
  CardPack3: true,
  InvBag21: true,
  InvBag22: true,
  InvBag23: true,
  InvBag24: true,
  InvBag25: true,
  InvBag26: true,
  InvStorage31: true,
  InvStorage32: true,
  InvStorage33: true,
  InvStorage34: true,
  InvStorage35: true,
  InvStorage36: true,
  InvStorage37: true,
  InvStorage38: true,
  InvStorage39: true,
  InvStorage40: true,
  InvStorage41: true,
  InvStorage42: true,
  COIN: true,
  EXP: true,
  Dreadlo: true,
  Godshard: true,
  DreadloBar: true,
  GodshardBar: true,
  AlienTree: true,
  TestObj18: true,
  TestObj9: true,
  TestObj10: true,
  EquipmentShirts7: true,
  EquipmentRingsChat2: true,
  EquipmentRingsChat3: true,
  EquipmentRingsChat4: true,
  EquipmentRingsChat5: true,
  EquipmentRingsChat6: true,
  EquipmentRingsChat8: true,
  EquipmentRingsChat9: true,
  EquipmentTools8: true,
  EquipmentTools9: true,
  EquipmentToolsHatchet6: true,
  EquipmentToolsHatchet8: true,
  EquipmentToolsHatchet9: true,
  EquipmentToolsHatchet10: true,
  Quest8: true,
  ClassSwap: true,
  ResetBox: true,
  Ht: true,
  StonePremRestore: true,
  SmithingRecipes3: true,
  SmithingRecipes4: true,
  EquipmentSmithingTabs4: true,
  Quest28: true,
  TrapBoxSet6: true,
  PCtoken8: true,
  StampB28: true,
  StampB29: true,
  StampB32: true,
  StampB33: true,
  StampB35: true,
  StampC10: true,
  StampC11: true,
  StampC12: true,
  ExpSmith1: true,
  StonePremSTR: true,
  StonePremAGI: true,
  StonePremWIS: true,
  StonePremLUK: true,
  GemP1: true,
  GemP9: true,
  GemP10: true,
  GemP11: true,
  GemP12: true,
  GemP13: true,
  GemP14: true,
  GemP15: true,
  GemQ9: true,
  EquipmentHats57: true,
  EquipmentHats45: true,
  EquipmentHats43: true,
  EquipmentHats37: true,
  EquipmentHats40: true,
  EquipmentHats36: true,
  EquipmentHats33: true,
  EquipmentHats32: true,
  EquipmentHats31: true,
  EquipmentHats34: true,
  CardsC13: true,
  CardsC14: true,
  CardsC15: true,
  CardsD12: true,
  CardsD13: true,
  Trophy4: true,
  Trophy7: true,
  Line8: true,
  Line9: true,
  Line11: true,
  Line12: true,
  Line13: true,
  Line14: true,
  Weight4: true,
  Weight7: true,
  Weight9: true,
  Weight13: true,
  Weight14: true,
  StampsA22: true,
  StampsA25: true,
  TalentPoint1: true,
  TalentPoint4: true,
  TalentPoint5: true,
  TalentPoint6: true,
  DoubleAFKtix: true,
  ObolFrag: true,
  StampC14: true,
  StampC15: true,
  DeliveryBox: true,
  StampC16: true,
  StampC17: true,
  StampC18: true,
  DungWeaponBow1: true,
  DungWeaponWand1: true,
  DungWeaponSword1: true,
  FishingRod1: true,
  CatchingNet1: true,
  DungRNG4: true,
  DungRNG3: true,
  DungEquipmentHats4: true, // might be released soon
  DungEquipmentPants4: true, // might be released soon
  DungEquipmentPendant4: true, // might be released soon
  DungEquipmentRings4: true, // might be released soon
  DungEquipmentShirt4: true, // might be released soon
  DungEquipmentShoes4: true, // might be released soon
  InvBag9: true, // might be released soon
  FoodHealth8: true,
  EquipmentCape1: true,
  EquipmentHats72: true,
  MaxCapBagFi0: true,
  MaxCapBagB0: true,
  MaxCapBagTr0: true,
  MaxCapBagTr2: true,
  MaxCapBagS0: true,
  MaxCapBagS2: true,
  StampA1: true,
  StampA2: true,
  Soul6: true,
  Spice0: true,
  Spice6: true,
  Spice9: true,
  Line4: true,
  EquipmentKeychain25: true,
  GemP19: true,
  EquipmentHats75: true,
  Quest70: true,
  Quest71: true,
};
