export const starSignsIndicesMap = {
  'The_Book_Worm': '1',
  'The_Buff_Guy': '1a',
  'The_Fuzzy_Dice': '1b',
  'Flexo_Bendo': '2',
  'Dwarfo_Beardus': '3',
  'Hipster_Logger': '4',
  'Pie_Seas': '4a',
  'Miniature_Game': '4b',
  'Shoe_Fly': '4c',
  'Pack_Mule': '5',
  'Pirate_Booty': '6',
  'All_Rounder': '7',
  'Muscle_Man': '7a',
  'Fast_Frog': '7b',
  'Smart_Stooge': '7c',
  'Lucky_Larry': '7d',
  'Fatty_Doodoo': '8',
  'Robinhood': '9',
  'Blue_Hedgehog': '9a',
  'Ned_Kelly': '10',
  'The_Fallen_Titan': '10a',
  'Chronus_Cosmos': 'CR',
  'Activelius': '11',
  'Gum_Drop': '11a',
  'Mount_Eaterest': '12',
  'Bob_Build_Guy': '13',
  'The_Big_Comatose': '14',
  'Sir_Savvy': '14a',
  'Silly_Snoozer': '15',
  'The_Big_Brain': '15a',
  'Grim_Reaper': '16',
  'The_Forsaken': '16a',
  'The_OG_Skiller': '17',
  'Mr_No_Sleep': '18',
  'All_Rounderi': '1',
  'Centaurii': '2',
  'Murmollio': '3',
  'Strandissi': '4',
  'Agitagi': '4B',
  'Wispommo': '5',
  'Lukiris': '5B',
  'Pokaminni': '6',
  'Gor_Bowzor': '7',
  'Hydron_Cosmos': '8',
  'Trapezoidburg': '8B',
  'Sawsaw_Salala': '9',
  'Preys_Bea': '9B',
  'Cullingo': '10',
  'Gum_Drop_Major': '10B',
  'Grim_Reaper_Major': '11',
  'Sir_Savvy_Major': '12',
  'The_Bulwark': '13',
  'Big_Brain_Major': '14',
  'The_Fiesty': '15',
  'The_Overachiever': '15B',
  'Comatose_Major': '16',
  'S._Snoozer_Major': '17',
  'Breedabilli': '18',
  'Gordonius_Major': '19',
  'Power_Bowower': '19b',
  'Scienscion': '20',
  'Artifosho': '21',
  'Divividov': '22',
  'C._Shanti_Minor': '23',
  'Muscle_Magnus': 'S',
  'Cropiovo_Minor': 'A1',
  'Fabarmi': 'A2',
  'O.G._Signalais': 'A3',
  'Lightspeed_Frog': 'A4',
  'Beanbie_Major': 'A5',
  'Damarian_Major': 'A6',
  'Lotto_Larrinald': 'A7',
  'Intellostooge': 'A8',
  'S._Tealio': 'B1',
  'Sneekee_E._X.': 'B2',
  'Jadaciussi': 'B3',
  'Druipi_Major': 'B4',
  'Sumo_Magno': 'B5',
  'Killian_Maximus': 'B6',
  'Seraph_Cosmos': 'SC',
  'Glimmer_of_Beyond': 'C1'
}

// TODO: check if able to pull from Z.js
export const skillIndexMap = {
  0: { name: 'character', icon: '' },
  1: { name: 'mining', icon: 'ClassIcons42' },
  2: { name: 'smithing', icon: 'ClassIcons43' },
  3: { name: 'chopping', icon: 'ClassIcons44' },
  4: { name: 'fishing', icon: 'ClassIcons45' },
  5: { name: 'alchemy', icon: 'ClassIcons46' },
  6: { name: 'catching', icon: 'ClassIcons47' },
  7: { name: 'trapping', icon: 'ClassIcons48' },
  8: { name: 'construction', icon: 'ClassIcons49' },
  9: { name: 'worship', icon: 'ClassIcons50' },
  10: { name: 'cooking', icon: 'ClassIcons51' },
  11: { name: 'breeding', icon: 'ClassIcons52' },
  12: { name: 'laboratory', icon: 'ClassIcons53' },
  13: { name: 'sailing', icon: 'ClassIcons54' },
  14: { name: 'divinity', icon: 'ClassIcons55' },
  15: { name: 'gaming', icon: 'ClassIcons56' },
  16: { name: 'farming', icon: 'ClassIcons57' },
  17: { name: 'sneaking', icon: 'ClassIcons58' },
  18: { name: 'summoning', icon: 'ClassIcons59' }
};

export const keysMap = {
  0: { name: 'Forest_Villa_Key', rawName: 'Key1' },
  1: { name: 'Efaunt\'s_Tomb_Key', rawName: 'Key2' },
  2: { name: 'Chizoar\'s_Cavern_Key', rawName: 'Key3' },
  3: { name: 'Troll\'s_Enclave_Key', rawName: 'Key4' },
  4: { name: 'Kruk\'s_Volcano_Key', rawName: 'Key5' }
};

export const filteredGemShopItems = [
  'EquipmentCape0',
  'EquipmentCape2',
  'EquipmentPendant28',
  'EquipmentRings31',
  'EquipmentRings32',
  'EquipmentRings33',
  'EquipmentHats80',
  'EquipmentHats34'
].toSimpleObject();

export const filteredLootyItems = [
  'Quest42',
  'Quest49',
  'Quest50',
  'EquipmentShoes2',
  'EquipmentPendant18',
  'TestObj4',
  'TestObj5',
  'TestObj8',
  'TestObj14',
  'TestObj15',
  'TestObj16',
  'EquipmentPants11',
  'EquipmentSmithingTabs7',
  'EquipmentSmithingTabs8',
  'Quest8',
  'StampB28',
  'StampB29',
  'StampB33',
  'StampB35',
  'CardsC13',
  'CardsC14',
  'CardsC15',
  'CardsD12',
  'CardsD13',
  'Trophy4',
  'Trophy7',
  'StampsA22',
  'StampsA25',
  'DoubleAFKtix',
  'ObolFrag',
  'DeliveryBox',
  'StampC17',
  'FishingRod1',
  'CatchingNet1',
  'FoodHealth8',
  'EquipmentCape1',
  'EquipmentHats72',
  'EquipmentHats55',
  'MaxCapBagFi0',
  'MaxCapBagB0',
  'MaxCapBagTr0',
  'MaxCapBagTr2',
  'MaxCapBagS0',
  'MaxCapBagS2',
  'Spice0',
  'Spice6',
  'Spice9',
  'StampC13',
  'TalentPoint5',
  // Dungeon unobtainable
  'DungWeaponSwordE5',
  'DungWeaponBowE5',
  'DungWeaponWandE5',
  'DungWeaponPunchE5',
  'DungWeaponPunchF1',
  'DungWeaponPunchF2',
  'DungWeaponPunchF3',
  'DungWeaponPunchF4',
  'DungWeaponPunchF5',
  'DungWeaponWandF1',
  'DungWeaponWandF2',
  'DungWeaponWandF3',
  'DungWeaponWandF4',
  'DungWeaponWandF5',
  'DungWeaponBowF1',
  'DungWeaponBowF2',
  'DungWeaponBowF3',
  'DungWeaponBowF4',
  'DungWeaponBowF5',
  'DungWeaponSwordF1',
  'DungWeaponSwordF2',
  'DungWeaponSwordF3',
  'DungWeaponSwordF4',
  'DungWeaponSwordF5',

  'DungEquipmentShoes4',
  'DungEquipmentShirt4',
  'DungEquipmentRings4',
  'DungEquipmentPants4',
].toSimpleObject();

export const skillsMaps = {
  mining: [6, 7, 9, 10, 11].toSimpleObject(),
  fishing: [54, 55, 61].toSimpleObject()
}