export const starSignsIndicesMap = {
  'The_Book_Worm': '1',
  'The_Buff_Guy': '1a',
  'The_Fuzzy_Dice': '1b',
  'Flexo_Bendo': '2',
  'Dwarfo_Beardus': '3',
  'Hipster_Logger': '4',
  'Pie_Seas': '4a',
  'Miniature_Game': '4b',
  'Shoe_Fly': '4c',
  'Pack_Mule': '5',
  'Pirate_Booty': '6',
  'All_Rounder': '7',
  'Muscle_Man': '7a',
  'Fast_Frog': '7b',
  'Smart_Stooge': '7c',
  'Lucky_Larry': '7d',
  'Fatty_Doodoo': '8',
  'Robinhood': '9',
  'Blue_Hedgehog': '9a',
  'Ned_Kelly': '10',
  'The_Fallen_Titan': '10a',
  'Chronus_Cosmos': 'CR',
  'Activelius': '11',
  'Gum_Drop': '11a',
  'Mount_Eaterest': '12',
  'Bob_Build_Guy': '13',
  'The_Big_Comatose': '14',
  'Sir_Savvy': '14a',
  'Silly_Snoozer': '15',
  'The_Big_Brain': '15a',
  'Grim_Reaper': '16',
  'The_Forsaken': '16a',
  'The_OG_Skiller': '17',
  'Mr_No_Sleep': '18',
  'All_Rounderi': '1',
  'Centaurii': '2',
  'Murmollio': '3',
  'Strandissi': '4',
  'Agitagi': '4B',
  'Wispommo': '5',
  'Lukiris': '5B',
  'Pokaminni': '6',
  'Gor_Bowzor': '7',
  'Hydron_Cosmos': '8',
  'Trapezoidburg': '8B',
  'Sawsaw_Salala': '9',
  'Preys_Bea': '9B',
  'Cullingo': '10',
  'Gum_Drop_Major': '10B',
  'Grim_Reaper_Major': '11',
  'Sir_Savvy_Major': '12',
  'The_Bulwark': '13',
  'Big_Brain_Major': '14',
  'The_Fiesty': '15',
  'The_Overachiever': '15B',
  'Comatose_Major': '16',
  'S._Snoozer_Major': '17',
  // "Unknown":"18",
  // "Unknown":"19",
  // "Unknown":"19B",
  // "Unknown":"20",
  // "Unknown":"21",
  // "Unknown":"22",
  // "Unknown":"23",
}

// TODO: check if able to pull from Z.js
export const skillIndexMap = {
  0: { name: 'character', icon: '' },
  1: { name: 'mining', icon: 'ClassIcons42' },
  2: { name: 'smithing', icon: 'ClassIcons43' },
  3: { name: 'chopping', icon: 'ClassIcons44' },
  4: { name: 'fishing', icon: 'ClassIcons45' },
  5: { name: 'alchemy', icon: 'ClassIcons46' },
  6: { name: 'catching', icon: 'ClassIcons47' },
  7: { name: 'trapping', icon: 'ClassIcons48' },
  8: { name: 'construction', icon: 'ClassIcons49' },
  9: { name: 'worship', icon: 'ClassIcons50' },
  10: { name: 'cooking', icon: 'ClassIcons51' },
  11: { name: 'breeding', icon: 'ClassIcons52' },
  12: { name: 'laboratory', icon: 'ClassIcons53' },
  13: { name: 'sailing', icon: 'ClassIcons54' },
  14: { name: 'divinity', icon: 'ClassIcons55' },
  15: { name: 'gaming', icon: 'ClassIcons56' },
};

export const keysMap = {
  0: { name: 'Forest_Villa_Key', rawName: 'Key1' },
  1: { name: 'Efaunt\'s_Tomb_Key', rawName: 'Key2' },
  2: { name: 'Chizoar\'s_Cavern_Key', rawName: 'Key3' },
  3: { name: 'Troll\'s_Enclave_Key', rawName: 'Key4' },
  4: { name: 'Kruk\'s_Volcano_Key', rawName: 'Key5' },
};

export const filteredGemShopItems = [
  'EquipmentCape0',
  'EquipmentCape2',
  'EquipmentPendant28',
  'EquipmentRings31',
  'EquipmentRings32',
  'EquipmentRings33',
  'EquipmentHats80',
  'EquipmentHats34'
].toSimpleObject();

export const filteredLootyItems = {
  Quest30: true,
  Quest42: true,
  Quest49: true,
  Quest50: true,
  Quest64: true,
  PalmTreeD: true,
  EquipmentShoes2: true,
  EquipmentPendant18: true,
  TestObj4: true,
  TestObj5: true,
  TestObj8: true,
  TestObj14: true,
  TestObj15: true,
  TestObj16: true,
  EquipmentPants11: true,
  EquipmentSmithingTabs6: true,
  EquipmentSmithingTabs7: true,
  EquipmentSmithingTabs8: true,
  EquipmentToolsHatchet10: true,
  Quest8: true,
  ClassSwap: true,
  ResetBox: true,
  Ht: true,
  SmithingRecipes3: true,
  SmithingRecipes4: true,
  Godshard: true,
  GodshardBar: true,
  Quest28: true,
  StampB28: true,
  StampB29: true,
  StampB32: true,
  StampB33: true,
  StampB35: true,
  StampC10: true,
  StampC11: true,
  StampC12: true,
  CardsC13: true,
  CardsC14: true,
  CardsC15: true,
  CardsD12: true,
  CardsD13: true,
  Trophy4: true,
  Trophy7: true,
  Line8: true,
  Line9: true,
  Line11: true,
  Line12: true,
  Line13: true,
  Line14: true,
  Weight4: true,
  Weight7: true,
  Weight9: true,
  Weight13: true,
  Weight14: true,
  StampsA22: true,
  StampsA25: true,
  DoubleAFKtix: true,
  ObolFrag: true,
  DeliveryBox: true,
  StampC17: true,
  FishingRod1: true,
  CatchingNet1: true,
  FoodHealth8: true,
  EquipmentCape1: true,
  EquipmentHats72: true,
  EquipmentHats55: true,
  EquipmentHats42: true,
  EquipmentHats63: true,
  EquipmentHats66: true,
  MaxCapBagFi0: true,
  MaxCapBagB0: true,
  MaxCapBagTr0: true,
  MaxCapBagTr2: true,
  MaxCapBagS0: true,
  MaxCapBagS2: true,
  Spice0: true,
  Spice6: true,
  Spice9: true,
  EquipmentHats75: true,
  Quest71: true,
  StampC13: true,
  TalentPoint5: true
};

export const skillsMaps = {
  mining: [6, 7, 9, 10, 11].toSimpleObject(),
  fishing: [54, 55, 61].toSimpleObject()
}