// Display names per wiki kind. Data-free so Node scripts (the entity-graph build) can import it
// without pulling MUI or React into the build graph.
export const KIND_LABELS = {
  item: 'Item',
  monster: 'Monster',
  npc: 'NPC',
  quest: 'Quest',
  achievement: 'Achievement',
  world: 'World',
  class: 'Class',
  talent: 'Talent',
  pet: 'Pet',
  bundle: 'Bundle',
  shop: 'Shop',
  station: 'Station',
  chip: 'Lab Chip',
  jewel: 'Lab Jewel',
  meal: 'Meal',
  spice: 'Spice',
  prayer: 'Prayer',
  building: 'Building',
  vault: 'Vault Upgrade',
  starsign: 'Star Sign',
  constellation: 'Constellation',
  postbox: 'Post Office Box',
  sigil: 'Sigil',
  arcade: 'Arcade Upgrade',
  god: 'Divinity God',
  artifact: 'Sailing Artifact',
  superbit: 'Gaming Superbit',
  equinox: 'Equinox Upgrade',
  jade: 'Jade Emporium Upgrade',
  map: 'Map',
  vial: 'Vial',
  bubble: 'Bubble'
};

// NPC pluralises without an s on the label itself, so this cannot be derived from KIND_LABELS.
export const KIND_PLURALS = {
  item: 'Items',
  monster: 'Monsters',
  npc: 'NPCs',
  quest: 'Quests',
  achievement: 'Achievements',
  world: 'Worlds',
  class: 'Classes',
  talent: 'Talents',
  pet: 'Pets',
  bundle: 'Bundles',
  shop: 'Shops',
  station: 'Stations',
  chip: 'Lab Chips',
  jewel: 'Lab Jewels',
  meal: 'Meals',
  spice: 'Spices',
  prayer: 'Prayers',
  building: 'Buildings',
  vault: 'Upgrade Vault',
  starsign: 'Star Signs',
  constellation: 'Constellations',
  postbox: 'Post Office Boxes',
  sigil: 'Sigils',
  arcade: 'Arcade Upgrades',
  god: 'Divinity Gods',
  artifact: 'Sailing Artifacts',
  superbit: 'Gaming Superbits',
  equinox: 'Equinox Upgrades',
  jade: 'Jade Emporium',
  map: 'Maps',
  vial: 'Vials',
  bubble: 'Bubbles'
};
