/**
 * Generates N smoke test spec files that each run a slice of all test cases.
 * Usage: node e2e/generate-specs.js [workerCount]
 * Default: 4 workers
 */
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const dir = dirname(fileURLToPath(import.meta.url));
const WORKER_COUNT = parseInt(process.argv[2]) || 4;

for (let i = 0; i < WORKER_COUNT; i++) {
  const lines = [
    '// Auto-generated by generate-specs.js — do not edit',
    "import { test, expect, getAllTestCases, clientNavigate, collectErrors } from './smoke-helpers.js';",
    '',
    "test.describe.configure({ mode: 'serial' });",
    '',
    'const allCases = getAllTestCases();',
    'const myCases = allCases.filter((_, idx) => idx % ' + WORKER_COUNT + ' === ' + i + ');',
    '',
    "test.describe('Smoke tests', () => {",
    '  for (const { name, path, query } of myCases) {',
    '    test(name, async ({ demoPage }) => {',
    '      const { errors, cleanup } = collectErrors(demoPage);',
    '      await clientNavigate(demoPage, path, query);',
    "      await expect(demoPage.locator('body')).not.toBeEmpty();",
    '      expect([...errors]).toEqual([]);',
    '      cleanup();',
    '    });',
    '  }',
    '});',
    '',
  ];
  writeFileSync(join(dir, 'smoke-' + i + '.spec.js'), lines.join('\n'));
}

console.log('Generated ' + WORKER_COUNT + ' spec files');
