// Leaderboard metric -> sprite under public/ (no extension). Boards without one get a monogram.
const SKILL_ICONS = {
  mining: 42, smithing: 43, choppin: 44, fishing: 45, alchemy: 46, catching: 47, trapping: 48, construction: 49,
  worship: 50, cooking: 51, breeding: 52, laboratory: 53, sailing: 54, divinity: 55, gaming: 56, farming: 57,
  sneaking: 58, summoning: 59, spelunking: 60, research: 61
};

// Picked by hand for every other board (2026-10-08); a sprite path under public/, no extension.
const METRIC_ICONS = {
  afkTime: 'data/Afkz5',
  anionicSaltRank: 'data/Refinery9',
  arenaWaves: 'data/ConTower9',
  bellPings: 'data/GalleryBell',
  bellRings: 'etc/Cavern_4',
  bestDenScore: 'etc/Cavern_2',
  bestJellyDps: 'data/JellyUpg18',
  bestSushiCombo: 'data/SushiButton1',
  biggestHaulSpelunking: 'data/CaveShopUpg0',
  bits: 'data/Bits_x1',
  brokenJars: 'etc/Cavern_10',
  cashMulti: 'data/Cash',
  cookingMasteryLevel: 'data/ClassIcons51',
  copperSample: 'data/Copper',
  crosslinkSaltRank: 'data/Refinery7',
  dartsMinigame: 'data/Quest104',
  dioxideSaltRank: 'data/Refinery4',
  dkOrbKills: 'data/UISkillIcon168',
  dropRate: 'data/LootDrop_x1',
  dungeonCredits: 'data/DungCredits1',
  dungeonFlurbos: 'data/DungCredits2',
  endlessSummoningWins: 'etc/Endless_Summoning',
  esWormholeKills: 'data/UISkillIcon498',
  explosiveSaltRank: 'data/Refinery2',
  fliesSample: 'data/Bug1',
  fractalHours: 'data/IslandSail5',
  glimboTotalTrades: 'afk_targets/Glimbo',
  globalRanking: 'data/Trophie',
  godRank: 'data/DivGod0',
  goldFishSample: 'data/Fish1',
  greenMushroomKills: 'monsters/mushG/static',
  highestArcaneMapMulti: 'data/StatusArc1',
  highestBigP: 'data/aUpgradesY21',
  highestCallMeAsh: 'data/aUpgradesG11',
  highestCallMeBob: 'data/aUpgradesO11',
  highestCogExp: 'data/CogCry5',
  highestColonyLevel: 'etc/Cavern_8',
  'highestConstructExp/hr': 'data/ClassIcons49',
  highestCropOg: 'data/FarmCrop0',
  highestHammerHammer: 'data/aUpgradesG2',
  highestJusticeRound: 'etc/Cavern_9',
  highestMegafeather: 'data/Feaz9',
  highestMegaFish: 'data/RooMG11',
  highestMegaFlesh: 'data/BubbaMF11',
  highestNugget: 'etc/GamingNugget',
  highestOutpostResourceRate: 'data/RGres1',
  highestPowerPet: 'data/GeneOver0',
  highestSanctumLevel: 'etc/Cavern_14',
  highestShowdownLevel: 'monsters/Boss6A/static',
  highestSpelunkingPower: 'data/CaveShopUpg17',
  'highestVillagerExp/hr': 'data/EquipmentStatues29',
  hoopsMinigame: 'data/HoopB',
  hp: 'data/UISkillIcon0',
  jadeCoins: 'etc/jade_coin',
  level: 'data/UpgArrowG',
  logBook: 'data/GamingPlant0',
  logSample: 'data/OakTree',
  mineheadOpponentsDefeated: 'data/MineHead0',
  monstersKilled: 'data/ObolPinkKill',
  mp: 'data/UISkillIcon1',
  nulloSaltRank: 'data/Refinery6',
  plantsPicked: 'data/FarmPlant6',
  postOfficeOrders: 'data/DeliveryBox',
  propagatedSaltRank: 'data/Refinery8',
  purpleSaltRank: 'data/Refinery5',
  redoxSaltRank: 'data/Refinery1',
  refinedSalts: 'data/Refinery1',
  sbPlunderousKills: 'data/UISkillIcon319',
  slab: 'etc/Slab',
  spontaneitySaltRank: 'data/Refinery3',
  sporeSample: 'data/Grasslands1',
  strength: 'etc/Character',
  totalAdviceFishUpgrades: 'data/W7_fish',
  totalArcanistUpgrades: 'data/StatusArc0',
  totalBoats: 'etc/Boat_Frame_1',
  totalBonesCollected: 'data/Bone0_x1',
  totalBraveryLevels: 'data/Bravery_Monument_x1',
  totalBreedabilityLevels: 'data/PetBrd9',
  totalBubbles: 'data/aBrewOptionA0',
  totalBuildings: 'data/ConTower7',
  totalButtonPresses: 'etc/ButtonG',
  totalCards: 'data/2CardsA0',
  totalCollectibleLevels: 'data/HoleJar0',
  totalCompassUpgrades: 'data/UISkillIcon421',
  totalCoralKidUpgrades: 'data/Coral0',
  totalDivinityBlessingLevels: 'data/ClassIcons55',
  totalDustCollected: 'data/Dust0_x1',
  totalEquinoxUpgrades: 'data/Quest78',
  totalFountainUpgrades: 'etc/Cavern_15',
  totalGambitTime: 'etc/Cavern_13',
  totalGamingCrowns: 'data/GamingRatCrown',
  totalGreenStacks: 'data/GreenSymbol',
  totalGrimoireUpgrades: 'data/GrimoireUpg18',
  totalJellyCellLevels: 'data/JellyUnit0',
  totalJellyUpgrades: 'data/JellyBut1',
  totalJusticeLevels: 'etc/Cavern_9',
  totalLevels: 'data/UpgArrowG',
  totalMaterialPrinted: 'data/PrintSlot',
  totalMeals: 'data/CookingM0',
  totalMeasurementLevels: 'etc/Villager_3',
  totalMedallions: 'data/WWcoin',
  totalMoney: 'data/Coins1',
  totalOpals: 'data/Opal',
  totalOutposts: 'data/RGfence_2',
  totalPlotRanks: 'etc/Seed_5',
  totalPrimeKills: 'etc/KillroyPrime',
  totalRoyalArmoryUpgrades: 'data/UISkillIcon226',
  totalRoyalResourceGrades: 'data/RGres0',
  totalRoyalStatueLevels: 'data/RGenh',
  totalShinyLevels: 'data/StampB28',
  totalShrines: 'data/ConTower9',
  totalSkillsLevels: 'data/BadgeD2',
  totalSpelunkingUpgrades: 'etc/Spelunking',
  totalStamps: 'data/StampA1',
  totalStatues: 'data/EquipmentStatues1',
  totalStringLevels: 'etc/Cavern_5',
  totalSummoningUpgrades: 'data/SummMob0',
  totalSushiKnowledgeLevels: 'data/SushiUpg13',
  totalSushiPerfectos: 'etc/SushiPerfectoStar',
  totalSushiStationUpgrades: 'data/Sushi6',
  totalTachyonsCollected: 'data/Tach0_x1',
  totalTomePoints: 'data/EquipmentNametagReplica28',
  totalVials: 'data/aVials1',
  'totalVillagerExp/hr': 'data/EquipmentStatues29',
  totalWaves: 'etc/SWR_Containment',
  totalZenithMarketUpgrades: 'data/Quest110',
  trashedCogs: 'data/Quest57',
  vwPortals: 'data/UISkillIcon45',
  w1Colo: 'data/TixCol',
  w2Colo: 'data/TixCol',
  w3Colo: 'data/TixCol',
  w4Colo: 'data/TixCol',
  w5Colo: 'data/TixCol',
  w6Colo: 'data/TixCol',
  whiteEssence: 'data/SummC1'
};

export const metricIcon = (metric) => {
  if (Object.hasOwn(SKILL_ICONS, metric)) return `data/ClassIcons${SKILL_ICONS[metric]}`;
  return Object.hasOwn(METRIC_ICONS, metric) ? METRIC_ICONS[metric] : null;
};

const FILLER = new Set(['Total', 'Highest', 'Best', 'Most', 'Biggest']);

export const monogram = (label = '') => {
  const words = label.split(/\s+/).filter(Boolean);
  const word = words.find((entry) => !FILLER.has(entry)) ?? words[0];
  return word ? word.slice(0, 2) : '?';
};
