import Head from "next/head";
import React, { useEffect, useState } from "react";
import styled from "styled-components";
import { prefix, cardsObject } from "../Utilities";
import { TextField, Chip, InputAdornment } from "@material-ui/core";
import ClearIcon from "@material-ui/icons/Clear";
import CustomTooltip from "../components/CustomTooltip";

export default function Home() {
  const [value, setValue] = useState("");
  const [localCardObject, setCardObject] = useState(cardsObject);
  const preConfiguredStats = [
    "Show All",
    "Choppin",
    "Mining",
    "Fishing",
    "Catching",
    "Accuracy",
    "Damage",
    "Drop Rate",
    "STR",
    "AGI",
    "WIS",
    "LUK",
  ];
  useEffect(() => {
    const newCards = Object.keys(cardsObject).reduce((res, cardSet) => {
      const cardsArr = cardsObject[cardSet];
      const sortedCardArr = cardsArr.filter(({ effect }) =>
        effect?.toLowerCase()?.includes(value.toLowerCase())
      );
      return { ...res, [cardSet]: sortedCardArr };
    }, {});
    setCardObject(newCards);
  }, [value]);

  return (
    <Wrapper>
      <Head>
        <title>Idleon Card Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${prefix}/favicon.ico`} />
      </Head>

      <Main>
        <h1>Search Cards by Stats</h1>
        <StyledTextField
          InputProps={{
            endAdornment: (
              <StyledInputAdornment onClick={() => setValue("")} position="end">
                <ClearIcon />
              </StyledInputAdornment>
            ),
          }}
          label="Enter Card stat.."
          type="text"
          value={value}
          onChange={({ target }) => setValue(target?.value)}
        />

        <div className="chips">
          {preConfiguredStats.map((stat, index) => (
            <Chip
              key={stat + "" + index}
              className="chip"
              size="small"
              variant="outlined"
              label={stat}
              onClick={() => {
                setValue(stat === "Show All" ? "" : stat);
              }}
            />
          ))}
        </div>

        <div className="cards">
          {Object.keys(localCardObject)?.length > 0 ? (
            Object.keys(localCardObject).map((cardSet, cardSetIndex) => {
              const cardsArr = localCardObject[cardSet];
              if (!cardsArr || cardsArr?.length === 0) return null;
              return (
                <React.Fragment key={cardSet + "" + cardSetIndex}>
                  <img
                    className="card-banner"
                    src={`${prefix}/${cardSet}_Cardbanner.png`}
                    alt=""
                  />
                  <div>
                    {cardsArr.map(({ img, effect, base }, index) => {
                      return (
                        <React.Fragment key={effect + "" + index}>
                          <CustomTooltip
                            header={
                              img.replace(/_/g, " ").replace(/Card.png/, "") +
                              " - " +
                              effect
                            }
                            base={base}
                          >
                            <img
                              className="card"
                              src={`${prefix}/cards/${img}`}
                              alt={effect}
                              height={72}
                              width={52}
                            />
                          </CustomTooltip>
                          {index === 7 ? <br /> : null}
                        </React.Fragment>
                      );
                    })}
                  </div>

                  {/* {cardSetIndex === 2} */}
                </React.Fragment>
              );
            })
          ) : (
            <div className="not-found">Please try another phrase</div>
          )}
        </div>
      </Main>
    </Wrapper>
  );
}

const Wrapper = styled.div`
  display: flex;
  justify-content: center;
`;

const StyledTextField = styled(TextField)`
  && label.Mui-focused {
    color: rgba(255, 255, 255, 0.7);
  }
  & .MuiInput-underline:after {
    border-bottom-color: green;
  }
`;

const StyledInputAdornment = styled(InputAdornment)`
  cursor: pointer;
`;

const Main = styled.main`
  color: white;
  width: 80%;

  .chips {
    margin: 20px 0;

    .chip {
      margin-right: 10px;
      margin-top: 8px;
    }
  }

  .cards {
    min-height: 600px;

    .card {
      margin: 5px 10px;
    }

    .card-banner {
      margin: 10px;
      display: block;
    }

    .not-found {
      margin: 20px;
      font-size: 30px;
    }
  }

  h1 {
    color: white;
  }
`;
